### ISSUE TITLE
Error in buoys worker, when parsing gif

### ISSUE THREAD

**Issue by DylanFM** [DylanFM/mhl-buoy-data#3]
https://bugsnag.com/errors/5125d6b3d0ae0b80248a5e02/events/newest

```
Feb 26 21:10:22 buoys app/scheduler.5165:  Error: Error: TypeError: Cannot read property '0' of undefined 
Feb 26 21:10:23 buoys app/scheduler.5165:      at /app/worker.coffee:34:21 
Feb 26 21:10:23 buoys app/scheduler.5165:      at parseMHLGraph (/app/node_modules/mhl-buoy-data/index.js:174:7) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at parseGif (/app/node_modules/mhl-buoy-data/gif.js:364:7) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at IncomingMessage.getImageData (/app/node_modules/mhl-buoy-data/gif.js:18:9) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at IncomingMessage.EventEmitter.emit (events.js:126:20) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at IncomingMessage._emitEnd (http.js:366:10) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at Socket.socketOnData [as ondata] (http.js:1367:20) 
Feb 26 21:10:23 buoys app/scheduler.5165:      at TCP.onread (net.js:403:27)
```

Image that's triggering this error:

![edeno-1](https://f.cloud.github.com/assets/14375/195756/fb8831ca-7ffd-11e2-92a9-f74359424973.gif)

**Comment by DylanFM** [comment]
Closed by de61cee1cb613c01e929704df1302e13d5ca47bd
Not fixing the error, but making it easier to handle up the stack.
